words = [
  "APBANKSEL",
  "APSEL",
  "DEVICEADDR",
  "DEVICEADDRTYPE",
  "Deassert",
  "Deasserting",
  "ERASEALLSTATUS",
  "ERASEPAGE",
  "IDR",
  "NFCPINS",
  "NRFFW",
  "NVMC",
  "VID",
  "approtect",
  "astro",
  "beforeunload",
  "bundler",
  "buttonless",
  "checksums",
  "cmsis",
  "codepagesize",
  "codesize",
  "crc",
  "dapjs",
  "dfu",
  "ebikes",
  "eraseall",
  "evenodd",
  "fflate",
  "ficr",
  "figcaption",
  "gnd",
  "keygen",
  "noopener",
  "nrf",
  "nrfutil",
  "oxlint",
  "patcher",
  "pselreset",
  "rarr",
  "sdcfw",
  "secp",
  "superduper",
  "swclk",
  "swdio",
  "uicr",
  "undownloaded",
  "usb",
  "webusb",
]
